export interface PublishedRoute { path: string; title: string; description: string; h1: string; canonical: string; indexable: boolean }
import { guides } from "./guides";
export const publicRoutes: PublishedRoute[] = [
  { path: "/", canonical: "/", indexable: true, title: "AI Metadata Cleaner — Free, Private & No Upload", description: "Use this free AI Metadata Cleaner to inspect image metadata and remove supported AI prompts and workflows locally. No upload or account required.", h1: "AI Metadata Cleaner for Images" },
  { path: "/metadata-checker", canonical: "/metadata-checker", indexable: true, title: "Image Metadata Checker — EXIF, XMP, C2PA & AI Data", description: "Check supported prompts, workflows, GPS, EXIF, XMP, ICC and C2PA locally before removing anything. Free, private and no account required.", h1: "Image Metadata Checker for EXIF, XMP and AI Data" },
  { path: "/remove-ai-detection-from-image", canonical: "/remove-ai-detection-from-image", indexable: true, title: "Remove AI Detection From an Image? What You Can Change", description: "Understand file metadata, visible artifacts and detector limits. Clean supported image metadata without guaranteed detector results.", h1: "Understand and Clean File-Level AI Signals" },
  { path: "/remove-metadata-from-png", canonical: "/remove-metadata-from-png", indexable: true, title: "Remove Metadata From PNG — Keep Transparency", description: "Remove supported AI workflow metadata from PNG files locally, without re-encoding image data. Supports EXIF privacy cleaning with output verification.", h1: "Remove Metadata From PNG Images" },
  { path: "/guides", canonical: "/guides", indexable: true, title: "Image Metadata Guides for Safer Publishing", description: "Practical explanations of EXIF, XMP, C2PA, prompts, privacy metadata and safe image handoff workflows.", h1: "Practical Image Metadata Guides" },
  ...guides.map((guide) => ({ path: `/guides/${guide.slug}`, canonical: `/guides/${guide.slug}`, indexable: true, title: guide.title, description: guide.description, h1: guide.h1 })),
  { path: "/pricing", canonical: "/pricing", indexable: true, title: "AI Metadata Remover Pricing — Free Daily Tools & Batch Pro", description: "Preview AI Metadata Remover plans: 1 free image a day for guests, 3 with an account, and Batch Pro at $4.99 every 30 days for 20 daily batch tasks. Subscriptions coming soon.", h1: "A little cleanup. Or a whole batch." },
  { path: "/about", canonical: "/about", indexable: true, title: "About This Local-First Metadata Workbench", description: "Why this workbench separates file evidence, safe cleaning and visible image quality without making detector promises.", h1: "How AI Metadata Remover Handles Your Files" },
  { path: "/privacy", canonical: "/privacy", indexable: true, title: "Privacy — Browser-Local Image Processing", description: "How Phase 1 keeps image bytes, file names and metadata values inside your browser session.", h1: "Your Image Stays in This Browser Session" },
  { path: "/terms", canonical: "/terms", indexable: true, title: "Terms — Image Metadata Tools", description: "The permitted uses, limitations and user responsibilities for these local image metadata tools.", h1: "Terms for Using the Metadata Tools" },
];
export const sitemapRoutes = publicRoutes.filter((route) => route.indexable).map((route) => route.path);
export function routeData(path: string) { const route = publicRoutes.find((item) => item.path === path); if (!route) throw new Error(`Unpublished route: ${path}`); return route; }
