export interface PublishedRoute { path: string; title: string; description: string; h1: string; canonical: string; indexable: boolean }
export const publicRoutes: PublishedRoute[] = [
  { path: "/", canonical: "/", indexable: true, title: "AI Metadata Cleaner & Remover — Free, Private Tool", description: "Inspect and remove supported prompts, workflows, GPS, EXIF, XMP and optional C2PA from images locally. Visual repair is not available yet.", h1: "Inspect and Clean AI Metadata Before You Publish" },
  { path: "/metadata-checker", canonical: "/metadata-checker", indexable: true, title: "Image Metadata Checker — EXIF, XMP, C2PA & AI Data", description: "Check supported prompts, workflows, GPS, EXIF, XMP, ICC and C2PA locally before removing anything. Free, private and no account required.", h1: "Check What Metadata Is Hidden in Your Image" },
  { path: "/remove-ai-detection-from-image", canonical: "/remove-ai-detection-from-image", indexable: true, title: "Remove AI Detection From an Image? What You Can Change", description: "Understand file metadata, visible artifacts and detector limits. Clean supported image metadata without guaranteed detector results.", h1: "Understand and Clean File-Level AI Signals" },
  { path: "/remove-metadata-from-png", canonical: "/remove-metadata-from-png", indexable: false, title: "Remove Metadata From PNG — Keep Transparency", description: "Review the local PNG metadata cleaner while the complete compatibility fixture gate is still in progress.", h1: "Remove Metadata From PNG Images" },
  { path: "/guides", canonical: "/guides", indexable: true, title: "Image Metadata Guides for Safer Publishing", description: "Practical explanations of EXIF, XMP, C2PA, prompts, privacy metadata and safe image handoff workflows.", h1: "Practical Image Metadata Guides" },
  { path: "/guides/image-metadata-before-publishing", canonical: "/guides/image-metadata-before-publishing", indexable: true, title: "What Image Metadata Should You Review Before Publishing?", description: "Learn which image metadata fields affect privacy, workflow confidentiality, attribution, color and provenance before you publish.", h1: "What Image Metadata Should You Review Before Publishing?" },
  { path: "/about", canonical: "/about", indexable: true, title: "About This Local-First Metadata Workbench", description: "Why this workbench separates file evidence, safe cleaning and visible image quality without making detector promises.", h1: "How ImageFinisher Handles Your Files" },
  { path: "/privacy", canonical: "/privacy", indexable: true, title: "Privacy — Browser-Local Image Processing", description: "How Phase 1 keeps image bytes, file names and metadata values inside your browser session.", h1: "Your Image Stays in This Browser Session" },
  { path: "/terms", canonical: "/terms", indexable: true, title: "Terms — Image Metadata Tools", description: "The permitted uses, limitations and user responsibilities for these local image metadata tools.", h1: "Terms for Using the Metadata Tools" },
];
export const sitemapRoutes = publicRoutes.filter((route) => route.indexable).map((route) => route.path);
export function routeData(path: string) { const route = publicRoutes.find((item) => item.path === path); if (!route) throw new Error(`Unpublished route: ${path}`); return route; }
