export interface PublishedRoute { path: string; title: string; description: string; h1: string; canonical: string; indexable: boolean }
import { guides } from "./guides";
export const publicRoutes: PublishedRoute[] = [
  { path: "/", canonical: "/", indexable: true, title: "AI Metadata Cleaner — Free, Private & No Upload", description: "Use this free AI Metadata Cleaner to inspect image metadata and remove supported AI prompts and workflows locally. No upload or account required.", h1: "AI Metadata Cleaner for Images" },
  { path: "/metadata-checker", canonical: "/metadata-checker", indexable: true, title: "Image Metadata Checker — EXIF, XMP, C2PA & AI Data", description: "Check supported prompts, workflows, GPS, EXIF, XMP, ICC and C2PA locally before removing anything. Free, private and no account required.", h1: "Image Metadata Checker for EXIF, XMP and AI Data" },
  { path: "/remove-ai-detection-from-image", canonical: "/remove-ai-detection-from-image", indexable: true, title: "Remove AI Detection From an Image? What You Can Change", description: "Understand file metadata, visible artifacts and detector limits. Clean supported image metadata without guaranteed detector results.", h1: "Understand and Clean File-Level AI Signals" },
  { path: "/remove-metadata-from-png", canonical: "/remove-metadata-from-png", indexable: true, title: "Remove Metadata From PNG — Keep Transparency", description: "Remove supported AI workflow metadata from PNG files locally, without re-encoding image data. Supports EXIF privacy cleaning with output verification.", h1: "Remove Metadata From PNG Images" },
  { path: "/batch-metadata-remover", canonical: "/batch-metadata-remover", indexable: true, title: "Batch Metadata Remover for JPEG & PNG Images", description: "Remove supported metadata from multiple JPEG or PNG images in your browser. Review each result and download completed copies with a batch summary.", h1: "Remove Metadata From Multiple Images" },
  { path: "/supported-formats", canonical: "/supported-formats", indexable: true, title: "JPEG, PNG & WebP Metadata Support", description: "Compare what this browser tool can inspect, remove and leave unresolved in JPEG, PNG and WebP files.", h1: "JPEG, PNG and WebP Metadata Support" },
  { path: "/comfyui-workflow-remover", canonical: "/comfyui-workflow-remover", indexable: true, title: "Remove ComfyUI Workflow From PNG — Local and Private", description: "Check and remove supported embedded ComfyUI workflow and prompt data from a static PNG copy in your browser, then review the result.", h1: "Remove Embedded ComfyUI Workflow Data" },
  { path: "/stable-diffusion-metadata-remover", canonical: "/stable-diffusion-metadata-remover", indexable: true, title: "Stable Diffusion Metadata Remover for PNG Images", description: "Remove supported Stable Diffusion prompts, seeds and sampler settings from a PNG copy. Check the verified result and any remaining fields.", h1: "Remove Stable Diffusion Prompts and Generation Settings" },
  { path: "/remove-metadata-from-jpeg", canonical: "/remove-metadata-from-jpeg", indexable: true, title: "Remove Metadata From JPEG and JPG Without Re-encoding", description: "Clean supported AI workflow and privacy fields from JPEG copies while preserving encoded image data, orientation and color profile.", h1: "Remove Metadata From JPEG and JPG Images" },
  { path: "/c2pa-metadata-checker", canonical: "/c2pa-metadata-checker", indexable: true, title: "C2PA Content Credentials Checker for Images", description: "Check supported embedded Content Credentials in JPEG, PNG or WebP locally. See presence and integrity status; issuer trust is not assessed.", h1: "Check C2PA Content Credentials in Images" },
  { path: "/remove-gps-from-photo", canonical: "/remove-gps-from-photo", indexable: true, title: "Remove GPS Metadata From Photos | JPEG & PNG", description: "Remove supported GPS and private EXIF fields from JPEG or PNG copies in your browser, then review what remains.", h1: "Remove GPS Metadata From Photos" },
  { path: "/blog", canonical: "/blog", indexable: true, title: "Image Metadata Blog — Practical Guides for Safer Publishing", description: "Evidence-bounded articles about EXIF, XMP, C2PA, prompts, privacy metadata and safer image handoff workflows.", h1: "Practical Image Metadata Articles" },
  ...guides.map((guide) => ({ path: `/blog/${guide.slug}`, canonical: `/blog/${guide.slug}`, indexable: true, title: guide.title, description: guide.description, h1: guide.h1 })),
  { path: "/pricing", canonical: "/pricing", indexable: true, title: "AI Metadata Remover Pricing — Free, Monthly & Yearly Plans", description: "Compare AI Metadata Remover pricing for Free, Pro Monthly and Pro Yearly image cleaning plans, including batch ZIP downloads and browser-local privacy.", h1: "A little cleanup. Or a whole batch." },
  { path: "/about", canonical: "/about", indexable: true, title: "About This Local-First Metadata Workbench", description: "Why this workbench separates file evidence, safe cleaning and visible image quality without making detector promises.", h1: "How AI Metadata Remover Handles Your Files" },
  { path: "/privacy", canonical: "/privacy", indexable: true, title: "Privacy — Browser-Local Image Processing", description: "How image bytes, file names and metadata values stay inside your browser session.", h1: "Your Image Stays in This Browser Session" },
  { path: "/terms", canonical: "/terms", indexable: true, title: "Terms — Image Metadata Tools", description: "The permitted uses, limitations and user responsibilities for these local image metadata tools.", h1: "Terms for Using the Metadata Tools" },
];
export const sitemapRoutes = publicRoutes.filter((route) => route.indexable).map((route) => route.path);
export function routeData(path: string) { const route = publicRoutes.find((item) => item.path === path); if (!route) throw new Error(`Unpublished route: ${path}`); return route; }
