import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { PublicHeader } from "@/components/layout/public-header";
import { PublicFooter } from "@/components/layout/public-footer";
import { metadataFor } from "@/lib/site";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  return slug === "image-metadata-before-publishing" ? metadataFor("/guides/image-metadata-before-publishing") : {};
}

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  if (slug !== "image-metadata-before-publishing") notFound();

  return <><PublicHeader /><main className="guide-page"><div className="page-container">
    <Link className="back-link" href="/guides"><ArrowLeft /> All guides</Link>
    <article className="editorial-island island">
      <p className="island-kicker">Metadata basics</p>
      <h1>What Image Metadata Should You Review Before Publishing?</h1>
      <p className="island-meta">Updated September 7, 2026</p>
      <p className="island-intro">An image file can carry much more than the pixels you see. Prompts, node graphs, locations, creator details, color profiles, and provenance records may all be tucked inside. Each serves a different purpose, so deleting everything by default is rarely the best move.</p>
      <div className="island-divider" />
      <h2>Start with what this copy is for</h2>
      <p>A private client preview does not need the same metadata as a portfolio image or an archive. Keep the master file, decide what the copy needs, and remove only the details you do not want to send with it.</p>
      <table>
        <thead><tr><th>Field group</th><th>Why it matters</th><th>Safe default</th></tr></thead>
        <tbody>
          <tr><td data-label="Field group">Prompt & workflow</td><td data-label="Why it matters">May reveal how the image was made</td><td data-label="Safe default">Remove from delivery copies</td></tr>
          <tr><td data-label="Field group">GPS & device IDs</td><td data-label="Why it matters">Can reveal a location or identify equipment</td><td data-label="Safe default">Remove for privacy</td></tr>
          <tr><td data-label="Field group">Creator & copyright</td><td data-label="Why it matters">Helps with credit and licensing</td><td data-label="Safe default">Review and usually keep</td></tr>
          <tr><td data-label="Field group">ICC profile</td><td data-label="Why it matters">Keeps colors looking consistent</td><td data-label="Safe default">Keep</td></tr>
          <tr><td data-label="Field group">C2PA</td><td data-label="Why it matters">Records where a file came from and how it changed</td><td data-label="Safe default">Review before deciding</td></tr>
        </tbody>
      </table>
      <p>In this workspace, AI Workflow Clean removes supported generation fields from JPEG and PNG files. GPS inspection is available, but Privacy Clean and Full Clean are not ready yet. If your delivery copy needs location data removed, use a tool that supports that operation and verify the result.</p>
      <h2>Provenance is not a probability</h2>
      <p>C2PA can tell you how a file was signed or edited. A software field might simply name an everyday editing app. Neither belongs in a percentage score or proves that an image was generated by AI.</p>
      <p>The <a href="https://spec.c2pa.org/specifications/2.2/explainer/Explainer.html">official C2PA explainer</a> describes Content Credentials as provenance records. This metadata checker identifies supported embedded records; it does not validate signatures or retrieve an external edit history.</p>
      <blockquote>If the evidence is uncertain, the result should say so. A confident-looking score does not make the evidence stronger.</blockquote>
      <h2>Check the new copy, not just the button</h2>
      <p>A cleaning process can finish even when a target field is still there. Scan the new file again and check what was removed, what stayed, and what the tool could not handle.</p>
      <p>Ready to remove supported workflow fields? Open the <Link href="/">AI Metadata Cleaner</Link> and keep your original file for comparison.</p>
      <Link className="island-cta" href="/metadata-checker">Inspect an image locally <ArrowRight /></Link>
    </article>
    <div className="next-guide"><span>Ready to try it?</span><Link href="/workspace">Open the full workspace <ArrowRight /></Link></div>
  </div></main><PublicFooter /></>;
}
