import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { PublicHeader } from "@/components/layout/public-header";
import { PublicFooter } from "@/components/layout/public-footer";
import { metadataFor, siteUrl } from "@/lib/site";
import { guideBySlug, guides } from "@/lib/guides";
export function generateStaticParams() { return guides.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const guide = guideBySlug((await params).slug); return guide ? metadataFor(`/guides/${guide.slug}`) : {}; }
export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const guide = guideBySlug((await params).slug); if (!guide) notFound();
  const jsonLd = [{ "@context": "https://schema.org", "@type": "Article", headline: guide.h1, description: guide.description, dateModified: guide.updatedIso, mainEntityOfPage: `${siteUrl}/guides/${guide.slug}`, author: { "@type": "Organization", name: "AI Metadata Remover" } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${siteUrl}/` }, { "@type": "ListItem", position: 2, name: "Guides", item: `${siteUrl}/guides` }, { "@type": "ListItem", position: 3, name: guide.h1, item: `${siteUrl}/guides/${guide.slug}` }] }];
  return <><PublicHeader /><main className="guide-page"><div className="page-container"><Link className="back-link" href="/guides"><ArrowLeft /> All guides</Link><article className="editorial-island island"><p className="island-kicker">{guide.kicker}</p><h1>{guide.h1}</h1><p className="island-meta">Updated {guide.updated}</p><p className="island-intro">{guide.answer}</p><div className="island-divider" />{guide.table && <table><thead><tr>{guide.table.headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{guide.table.rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td data-label={guide.table?.headers[index]} key={`${row[0]}-${index}`}>{cell}</td>)}</tr>)}</tbody></table>}{guide.steps && <><h2>Use the automatic cleaner step by step</h2>{guide.steps.map((step, index) => <section key={step.title}><h3>{index + 1}. {step.title}</h3><p>{step.body}</p></section>)}</>}{guide.sections.map((section) => <section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}<h2>What this tool cannot promise</h2><ul>{guide.limits.map((limit) => <li key={limit}>{limit}</li>)}</ul><h2>Quick answer</h2><p><strong>{guide.faq.question}</strong> {guide.faq.answer}</p><div className="guide-tools"><strong>Related tools</strong>{guide.tools.map((tool) => <Link href={tool.href} key={tool.href}>{tool.label} <ArrowRight /></Link>)}</div><p className="guide-source">Primary source: <a href={guide.source.href} rel="noopener noreferrer">{guide.source.label}</a>.</p><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /></article></div></main><PublicFooter /></>;
}
