import Link from "next/link";
import { ArrowRight, Boxes, Eye, FileCheck2, ScanSearch, Sparkles } from "lucide-react";
import { PublicFooter } from "@/components/layout/public-footer";
import { PublicHeader } from "@/components/layout/public-header";
import { FAQSection } from "@/components/marketing/faq-section";
import { UnifiedImageWorkspace } from "@/components/tool/unified-image-workspace";

const faqs = [
  { question: "Does the image leave my browser?", answer: "No. Phase 1 scanning, cleaning, verification and downloads run in your browser. The site does not upload the image or its filename." },
  { question: "Does removing metadata make an image undetectable?", answer: "No. Metadata is only one layer. Platforms may use pixel-level watermarks, provenance systems or classifiers that this tool cannot control." },
  { question: "What does AI Workflow Clean remove?", answer: "It targets supported prompt, workflow, model, seed, sampler and related generation fields while preserving camera data, attribution, color profiles and orientation by default." },
  { question: "Will this lower image quality?", answer: "Supported container-level cleaning does not re-encode the encoded image payload. The verification card reports only what the output scan can prove." },
];

export default function Home() {
  return <><PublicHeader /><main>
    <section className="hero-section"><div className="hero-orbit" aria-hidden="true"><span /><span /><span /></div><div className="page-container hero-copy"><p className="eyebrow"><span className="status-dot" /> Private, browser-local image tools</p><h1>Inspect and Clean AI Metadata Before You Publish</h1><p className="hero-lede">Check prompts, workflows, C2PA, EXIF, GPS and other image metadata locally. Clean only what you choose, then use optional AI repair for visible artifacts.</p><p className="hero-status">Local metadata tools are live. Visual repair is not available yet.</p></div><div className="page-container hero-tool"><UnifiedImageWorkspace variant="embedded" defaultMode="inspect" /></div></section>
    <section className="section section-alt"><div className="page-container"><div className="section-heading split-heading"><div><p className="eyebrow">One file session</p><h2>Four steps. One deliberate handoff.</h2></div><p>See the file-level evidence, remove only supported fields, rescan the new bytes, then download a separate copy.</p></div><div className="capability-grid">
      <article><span className="step-number">01</span><ScanSearch /><h3>Inspect</h3><p>Surface prompt, workflow, privacy, provenance, camera and color information in plain language.</p></article>
      <article><span className="step-number">02</span><Boxes /><h3>Clean</h3><p>AI Workflow Clean is active. Privacy and Full Clean remain visible but gated until the extended format fixtures pass.</p></article>
      <article><span className="step-number">03</span><FileCheck2 /><h3>Verify</h3><p>The clean copy is scanned again. Removed and preserved states come from output evidence.</p></article>
      <article className="muted-capability"><span className="step-number">Later</span><Sparkles /><h3>Humanize</h3><p>Visual repair is not available yet. It will ship only after real provider results pass quality review.</p></article>
    </div></div></section>
    <section className="section"><div className="page-container evidence-layout"><div><p className="eyebrow">Inspector language</p><h2>Evidence without a made-up score</h2><p className="section-lede">A metadata field can be worth removing, worth reviewing, or purely informational. That is different from claiming the image “is AI.”</p><Link href="/metadata-checker" className="text-link">Open the metadata checker <ArrowRight /></Link></div><div className="sample-inspector"><div className="sample-head"><span>Example findings</span><span>3 fields</span></div><div className="sample-row"><span><b>AI generation parameters</b><small>Prompt, seed and sampler</small></span><em className="sample-action">Action suggested</em></div><div className="sample-row"><span><b>Content Credentials</b><small>Provenance and edit history</small></span><em className="sample-review">Review first</em></div><div className="sample-row"><span><b>Color profile</b><small>Consistent color display</small></span><em className="sample-info">Informational</em></div><p className="sample-note"><Eye /> Software or C2PA alone does not prove AI generation.</p></div></div></section>
    <section className="section section-alt"><div className="page-container"><div className="section-heading"><p className="eyebrow">Built for handoff</p><h2>Useful at the moment an image leaves your desk</h2></div><div className="use-case-grid"><article><p>AI CREATOR</p><h3>Remove internal workflow details</h3><span>Send a client copy without shipping the prompt, seed or node graph.</span></article><article><p>COMMERCE TEAM</p><h3>Preserve the image itself</h3><span>Keep encoded pixels, dimensions, transparency and color profile where the format permits.</span></article><article><p>PRIVACY CHECK</p><h3>Review location and identity fields</h3><span>Separate sensitive GPS and device details from useful attribution and camera data.</span></article></div></div></section>
    <section className="section boundary-section"><div className="page-container boundary-grid"><div><p className="eyebrow">Capability boundary</p><h2>File metadata is not the whole image</h2></div><div className="boundary-list"><p><b>We can inspect</b><span>Supported JPEG, PNG and WebP container metadata.</span></p><p><b>We can clean</b><span>Supported JPEG and PNG fields without re-encoding the image payload.</span></p><p><b>We cannot promise</b><span>Detector outcomes, platform approval, pixel-watermark removal or visual repair.</span></p></div></div></section>
    <FAQSection title="Questions before you clean" items={faqs} />
    <section className="section section-alt"><div className="page-container closing-card"><div><p className="eyebrow">Keep the master</p><h2>Make a new, inspectable delivery copy.</h2><p>Your original file is never overwritten.</p></div><Link href="/workspace" className="button primary">Open workspace <ArrowRight /></Link></div></section>
  </main><PublicFooter /></>;
}
