import Link from "next/link";
import { ArrowRight, Boxes, Eye, FileCheck2, ScanSearch, Sparkles } from "lucide-react";
import { PublicFooter } from "@/components/layout/public-footer";
import { PublicHeader } from "@/components/layout/public-header";
import { FAQSection } from "@/components/marketing/faq-section";
import { UnifiedImageWorkspace } from "@/components/tool/unified-image-workspace";

const faqs = [
  { question: "Does the image leave my browser?", answer: "No. Scanning, cleaning, verification, and downloads all happen in your browser. We never upload the image or its filename." },
  { question: "Does removing metadata make an image undetectable?", answer: "No. Metadata is only one signal. Platforms may also look at pixels, watermarks, provenance records, or signals this tool cannot access." },
  { question: "What does AI Workflow Clean remove?", answer: "It removes supported prompt, workflow, model, seed, sampler, and related generation fields. Camera data, attribution, color profiles, and orientation stay by default." },
  { question: "Will this lower image quality?", answer: "For supported files, cleaning does not re-encode the image data. Afterward, the verification card tells you exactly what the new scan found." },
];

export default function Home() {
  return <><PublicHeader /><main>
    <section className="hero-section"><div className="hero-orbit" aria-hidden="true"><span /><span /><span /></div><div className="page-container hero-copy"><p className="eyebrow"><span className="status-dot" /> Private image tools that run in your browser</p><h1>Inspect and Clean AI Metadata Before You Publish</h1><p className="hero-lede">See what is tucked inside your image: prompts, workflows, C2PA, EXIF, GPS, and more. Remove the fields you do not want to share, right in your browser.</p><p className="hero-status">Metadata tools are ready to use. Visual repair is still on the way.</p></div><div className="page-container hero-tool"><UnifiedImageWorkspace variant="embedded" defaultMode="inspect" /></div></section>
    <section className="section section-alt"><div className="page-container"><div className="section-heading split-heading"><div><p className="eyebrow">One file, one session</p><h2>What happens after you choose an image</h2></div><p>Check what is in the file, remove the supported fields you choose, scan the result again, and download a separate copy.</p></div><div className="capability-grid">
      <article><span className="step-number">01</span><ScanSearch /><h3>Inspect</h3><p>See prompt, workflow, privacy, provenance, camera, and color data in plain English.</p></article>
      <article><span className="step-number">02</span><Boxes /><h3>Clean</h3><p>AI Workflow Clean is ready now. Privacy Clean and Full Clean will unlock after they pass our extended file tests.</p></article>
      <article><span className="step-number">03</span><FileCheck2 /><h3>Verify</h3><p>We scan the new copy again, so you can see what was removed and what stayed.</p></article>
      <article className="muted-capability"><span className="step-number">Later</span><Sparkles /><h3>Humanize</h3><p>Visual repair is not ready yet. We will add it only after real provider results pass a quality review.</p></article>
    </div></div></section>
    <section className="section"><div className="page-container evidence-layout"><div><p className="eyebrow">What the scan tells you</p><h2>The scan reports fields, not probabilities</h2><p className="section-lede">Some fields are safe to remove. Others deserve a closer look or are simply useful information. None of them, on their own, proves that an image is AI-generated.</p><Link href="/metadata-checker" className="text-link">Open the metadata checker <ArrowRight /></Link></div><div className="sample-inspector"><div className="sample-head"><span>Example findings</span><span>3 fields</span></div><div className="sample-row"><span><b>AI generation parameters</b><small>Prompt, seed and sampler</small></span><em className="sample-action">Action suggested</em></div><div className="sample-row"><span><b>Content Credentials</b><small>Provenance and edit history</small></span><em className="sample-review">Review first</em></div><div className="sample-row"><span><b>Color profile</b><small>Consistent color display</small></span><em className="sample-info">Informational</em></div><p className="sample-note"><Eye /> Editing software or C2PA alone does not prove AI generation.</p></div></div></section>
    <section className="section section-alt"><div className="page-container"><div className="section-heading"><p className="eyebrow">Before you send the file</p><h2>Clean up what travels with your image</h2></div><div className="use-case-grid"><article><p>AI CREATOR</p><h3>Keep your workflow private</h3><span>Send clients a copy without the prompt, seed, or node graph attached.</span></article><article><p>COMMERCE TEAM</p><h3>Leave the image data alone</h3><span>Keep the encoded pixels, dimensions, transparency, and color profile when the format allows it.</span></article><article><p>PRIVACY CHECK</p><h3>Check location and device details</h3><span>Remove sensitive GPS or device data without automatically stripping useful attribution and camera information.</span></article></div></div></section>
    <section className="section boundary-section"><div className="page-container boundary-grid"><div><p className="eyebrow">What the tool can do</p><h2>Metadata is only one part of an image</h2></div><div className="boundary-list"><p><b>We can inspect</b><span>Supported metadata inside JPEG, PNG, and WebP files.</span></p><p><b>We can clean</b><span>Supported JPEG and PNG fields without re-encoding the image data.</span></p><p><b>We cannot promise</b><span>A particular detector result, platform approval, pixel-watermark removal, or visual repair.</span></p></div></div></section>
    <FAQSection title="A few things to know before cleaning" items={faqs} />
    <section className="section section-alt"><div className="page-container closing-card"><div><p className="eyebrow">Keep your original</p><h2>Download a separate copy you can check.</h2><p>We never overwrite the file you started with.</p></div><Link href="/workspace" className="button primary">Open workspace <ArrowRight /></Link></div></section>
  </main><PublicFooter /></>;
}
