import Link from "next/link";
import Image from "next/image";
import { metadataFor, siteUrl } from "@/lib/site";
import { appSchema, websiteSchema } from "@/lib/structured-data";
import { routeData } from "@/lib/publishing";

export const metadata = metadataFor("/");
import { ArrowRight, Boxes, Eye, FileCheck2, ScanSearch, Download } from "lucide-react";
import { PublicFooter } from "@/components/layout/public-footer";
import { PublicHeader } from "@/components/layout/public-header";
import { FAQSection } from "@/components/marketing/faq-section";
import { UnifiedImageWorkspace } from "@/components/tool/unified-image-workspace";

const faqs = [
  { question: "Which image formats can I clean?", answer: "AI Workflow Clean removes supported generation fields from JPEG and PNG files. WebP is inspection-only. Not every metadata field is supported, so review the verification report before sharing the result." },
  { question: "Does the image leave my browser?", answer: "No. Scanning, cleaning, verification, and downloads happen in your browser. The tool does not upload your image or its filename, and no account is required." },
  { question: "Can I remove GPS and EXIF data?", answer: "You can inspect supported GPS and EXIF fields, but Privacy Clean and Full Clean are not available yet. AI Workflow Clean keeps camera, location, and attribution information by default; it is not a general EXIF eraser." },
  { question: "Will this lower image quality?", answer: "For supported files, cleaning does not decode or re-encode the image data. The tool scans the output again and checks that the browser can read it before offering a download. Keep your original and review the copy." },
  { question: "Can I remove Content Credentials?", answer: "For supported PNG files, you can choose to remove embedded caBX Content Credentials. This option is off by default. JPEG and WebP provenance data are inspection-only. Removing an embedded record does not erase external provenance records." },
  { question: "Does removing metadata make an image undetectable?", answer: "No. Metadata is only one signal. Platforms may also use pixels, watermarks, provenance records, or signals this tool cannot access. A cleaned copy does not guarantee a detector result or platform approval." },
  { question: "How can I verify the cleaned copy?", answer: "Read the verification card after cleaning to see what was removed, preserved, or left unresolved. You can also open the downloaded copy in the metadata checker and scan it again. A completed download does not mean every metadata field was removed." },
  { question: "Are there file or batch limits?", answer: "Each file can be up to 25 MB. The desktop workspace accepts up to 30 files and 200 MB per batch; narrower mobile layouts accept up to 10 files and 100 MB. Processing time depends on your device and files." },
];

export default function Home() {
  return <><PublicHeader /><main className="home-page">
    <section className="hero-section"><div className="hero-orbit" aria-hidden="true"><span /><span /><span /></div><div className="page-container hero-copy"><p className="eyebrow"><span className="status-dot" /> Private image tools that run in your browser</p><h1>AI Metadata Cleaner for Images</h1><p className="hero-lede">See what your image contains before you share it. This free AI Metadata Cleaner removes supported prompts and workflow data from JPEG and PNG files in your browser. Inspect WebP metadata too, then review what was removed and what stayed.</p><p className="hero-status">No upload. No account. Your original stays unchanged.</p></div><div className="page-container hero-tool"><UnifiedImageWorkspace variant="embedded" defaultMode="inspect" /></div></section>
    <section className="section section-alt"><div className="page-container"><div className="section-heading split-heading"><div><p className="eyebrow">One file, one session</p><h2>How to Inspect, Clean, and Verify Your Image</h2></div><p>Check what is in the file, remove the supported fields you choose, scan the result again, and download a separate copy.</p></div><div className="capability-grid">
      <article><span className="step-number">01</span><ScanSearch /><h3>Inspect</h3><p>See prompt, workflow, privacy, provenance, camera, and color data in plain English.</p></article>
      <article><span className="step-number">02</span><Boxes /><h3>Clean</h3><p>Choose AI Workflow Clean to remove supported generation fields. Privacy Clean and Full Clean are not available yet.</p></article>
      <article><span className="step-number">03</span><FileCheck2 /><h3>Verify</h3><p>We scan the new copy again, so you can see what was removed and what stayed.</p></article>
      <article><span className="step-number">04</span><Download /><h3>Download</h3><p>Save a separate copy after reviewing the verification report. Your original file stays untouched.</p></article>
    </div></div></section>
    <section className="section"><div className="page-container evidence-layout"><div><p className="eyebrow">What the scan tells you</p><h2>What This AI Metadata Cleaner Can Remove</h2><p className="section-lede">Remove recognized generation fields such as prompts, node workflows, model settings, seeds, and samplers from supported JPEG and PNG structures. These fields may reveal how an image was made. A software name or C2PA record alone does not prove AI generation. Mixed or unsupported metadata can remain; check the result before sharing.</p><Link href="/metadata-checker" className="text-link">Open the metadata checker <ArrowRight /></Link></div><div className="sample-inspector"><div className="sample-head"><span>Example findings</span><span>3 fields</span></div><div className="sample-row"><span><b>AI generation parameters</b><small>Prompt, seed and sampler</small></span><em className="sample-action">Action suggested</em></div><div className="sample-row"><span><b>Content Credentials</b><small>Provenance and edit history</small></span><em className="sample-review">Review first</em></div><div className="sample-row"><span><b>Color profile</b><small>Consistent color display</small></span><em className="sample-info">Informational</em></div><p className="sample-note"><Eye /> Editing software or C2PA alone does not prove AI generation.</p></div></div></section>
    <section className="section section-alt"><div className="page-container"><div className="section-heading"><p className="eyebrow">Choose the right file</p><h2>Supported Formats and Cleaning Options</h2><p>Inspection and removal have different limits. This table describes the options currently available in the workspace.</p></div><div className="metadata-table-wrap"><table className="metadata-table"><caption>Current image metadata capabilities</caption><thead><tr><th scope="col">Capability</th><th scope="col">JPEG</th><th scope="col">PNG</th><th scope="col">WebP</th></tr></thead><tbody><tr><th scope="row">Inspect supported metadata</th><td>Yes</td><td>Yes</td><td>Yes</td></tr><tr><th scope="row">Clean supported AI workflow fields</th><td>Yes</td><td>Yes</td><td>Inspection only</td></tr><tr><th scope="row">Remove embedded C2PA</th><td>Inspection only</td><td>Optional caBX removal</td><td>Inspection only</td></tr><tr><th scope="row">Privacy / Full Clean</th><td>Not available</td><td>Not available</td><td>Not available</td></tr></tbody></table></div><p className="section-lede">JPEG metadata that mixes workflow details with attribution or camera fields may be preserved. Compressed PNG text that cannot be inspected safely also stays in place. Supported does not mean every field in every file.</p><Link href="/remove-metadata-from-png" className="text-link">Read the PNG cleaner limitations <ArrowRight /></Link></div></section>
    <section className="section"><div className="page-container"><div className="section-heading"><p className="eyebrow">Try the built-in sample</p><h2>What Changes—and What Stays</h2><p>The safe sample is a one-pixel PNG with a parameters field containing steps=30, seed=42, and sampler=euler. It is a test file, not a customer result.</p></div><div className="info-grid"><article><h3>Before cleaning</h3><p>The scanner finds one AI generation parameters field. Choose “Try a safe sample” in the tool above to inspect it yourself.</p></article><article><h3>After AI Workflow Clean</h3><p>The supported parameters text chunk is removed. The PNG image data stays unchanged; the tool scans the new copy and checks that it can still be opened.</p></article><article><h3>For your own files</h3><p>Results depend on the format and fields present. Camera information, attribution, orientation, and color data stay by default. Review unresolved findings instead of assuming the whole file is metadata-free.</p></article></div><figure className="metadata-preview"><Image src="/images/metadata-cleaner-preview.png" width={1200} height={630} alt="Verification view after cleaning the built-in PNG sample in ImageFinisher" unoptimized /><figcaption>Actual workspace using the built-in sample. Your file may contain different fields.</figcaption></figure><p className="section-lede">For a field-by-field explanation, read <Link href="/guides/image-metadata-before-publishing">what image metadata to review before publishing</Link>. To check a downloaded copy, use the <Link href="/metadata-checker">Image Metadata Checker</Link>.</p></div></section>
    <section className="section section-alt"><div className="page-container"><div className="section-heading"><p className="eyebrow">Before you send the file</p><h2>Clean up what travels with your image</h2></div><div className="use-case-grid"><article><p>AI CREATOR</p><h3>Keep your workflow private</h3><span>Send clients a copy without the prompt, seed, or node graph attached.</span></article><article><p>COMMERCE TEAM</p><h3>Leave the image data alone</h3><span>Keep the encoded pixels, dimensions, transparency, and color profile when the format allows it.</span></article><article><p>PRIVACY CHECK</p><h3>Check location and device details</h3><span>Check whether your image contains GPS or device details before sharing it. Privacy Clean is not available yet.</span></article></div></div></section>
    <section className="section boundary-section"><div className="page-container boundary-grid"><div><p className="eyebrow">What the tool can do</p><h2>Metadata is only one part of an image</h2></div><div className="boundary-list"><p><b>We can inspect</b><span>Supported metadata inside JPEG, PNG, and WebP files.</span></p><p><b>We can clean</b><span>Supported AI workflow fields in JPEG and PNG, without re-encoding the image data. Optional C2PA removal applies to PNG caBX records only.</span></p><p><b>We cannot promise</b><span>A particular detector result, platform approval, or pixel-watermark removal. Visual repair is not ready yet.</span></p></div></div></section>
    <div className="page-container"><p className="section-lede">For background on provenance, see the <a href="https://spec.c2pa.org/specifications/2.2/explainer/Explainer.html">official C2PA and Content Credentials explainer</a>. Finding an embedded record is different from validating its signature or checking an external provenance history.</p></div>
    <FAQSection title="Questions About AI Metadata Removal" items={faqs} />
    <section className="section section-alt"><div className="page-container closing-card"><div><p className="eyebrow">Keep your original</p><h2>Download a separate copy you can check.</h2><p>Use the AI Metadata Cleaner to make a delivery copy, then review the result. We never overwrite the file you started with.</p></div><Link href="/workspace" className="button primary">Open workspace <ArrowRight /></Link></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(appSchema("ImageFinisher AI Metadata Cleaner", routeData("/").description, `${siteUrl}/`)) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema(siteUrl)) }} />
  </main><PublicFooter /></>;
}
