import Link from "next/link";
import { LegalPage, type LegalSection } from "@/components/marketing/legal-page";
import { metadataFor, siteUrl } from "@/lib/site";

export const metadata = metadataFor("/terms");

const sections: LegalSection[] = [
  { id: "scope", title: "About these terms", content: <><p>These terms describe use of ImageFinisher’s browser-based image metadata tools at <a href={siteUrl}>aimetadateremover.pro</a>. The operator’s legal identity and a working support contact must be confirmed before this draft takes effect.</p><p>The service is intended for adults aged 18 or older who can enter into an agreement. If you act for an organization, you must be authorized to do so. Once effective, using the service is subject to these terms; do not use it if you do not agree.</p></> },
  { id: "service", title: "What the service does", content: <><p>You can inspect supported image metadata, remove supported fields from JPEG and PNG files and download a separate copy. WebP inspection is available; WebP cleaning is not. The tools run in your browser and do not require an account.</p><p>Full Clean and AI visual repair are not available in this version. The tool does not generate an authenticity certificate, determine copyright ownership or provide a reliable AI detection score. See the <Link href="/metadata-checker">Metadata Checker</Link> and <Link href="/remove-ai-detection-from-image">detection limits</Link> for product details.</p></> },
  { id: "fees", title: "Fees, cancellation and refunds", content: <><p>The current tools are free. This version does not sell subscriptions or credits, collect payment details, automatically renew a plan or charge for downloads. There is no paid subscription to cancel and no purchase through this version to refund.</p><p>You can stop using the service at any time by closing the page. If paid features are introduced, pricing, payment processing, renewal authorization, cancellation and refund conditions must be provided before purchase. Using the free tool does not authorize future charges.</p></> },
  { id: "responsibilities", title: "Your files and responsibilities", content: <><p>Only process files you own or have permission to use and modify. Keep the original and inspect each downloaded copy before publishing or sharing it. You remain responsible for image content, privacy permissions, attribution and any disclosure rules that apply to your use.</p><p>A successful verification concerns the checks the tool actually performs. It does not establish that every private or provenance field is gone, or that another platform will accept or classify the image in a particular way.</p></> },
  { id: "acceptable-use", title: "Permitted and prohibited use", content: <><p>You may use the tools to understand file metadata, remove supported private information or prepare an authorized publishing copy.</p><ul><li>Do not use metadata removal to create false evidence, conceal infringement, impersonate someone or mislead others about an image’s origin.</li><li>Do not violate copyright, privacy, child protection or other applicable laws.</li><li>Do not falsify camera, GPS, capture-date or provenance records, or use the service to remove visible copyright watermarks.</li><li>Do not interfere with the website, exploit its security controls or use it for malicious activity.</li></ul><p>Content Credentials describe provenance; they are not an AI verdict. Optional removal of supported PNG credentials is off by default and does not remove your disclosure obligations.</p></> },
  { id: "ownership", title: "Ownership and intellectual property", content: <><p>You retain the rights you already hold in your images. Processing a file does not transfer ownership to ImageFinisher or grant you rights held by another person. A cleaned copy does not create new copyright clearance.</p><p>The current local tools do not upload your images, train models on them or require a license to publish them. Rights in the website, software and branding remain with their respective owners, subject to any applicable open-source licenses.</p></> },
  { id: "privacy", title: "Privacy and third-party services", content: <><p>Read the <Link href="/privacy">Privacy Policy</Link> for local file processing, temporary diagnostics and ordinary website requests. The current image tools do not depend on a third-party AI generation API or payment checkout.</p><p>External links may lead to services governed by separate terms. ImageFinisher does not control how those services handle files you choose to give them.</p></> },
  { id: "limits", title: "Technical limits and availability", content: <><p>Unsupported, damaged, oversized or unusually structured files may be rejected. Some metadata can remain unresolved. Browser memory, device capability and format support can affect processing. Keep backups; the workspace is not a file storage or recovery service.</p><p>Features may be changed or discontinued. Do not rely on uninterrupted access or on the tool as your only way to preserve a file.</p></> },
  { id: "liability", title: "Disclaimers and legal rights", content: <><p>To the extent permitted by applicable law, the tools are provided as available without a guarantee of fitness for a particular purpose, complete metadata removal or a particular detector or platform outcome. They do not provide legal advice or certify authenticity.</p><p>To the extent permitted by law, the operator is not responsible for indirect or consequential losses arising from use of the tools. Nothing in these terms excludes liability that cannot legally be excluded or limits mandatory consumer rights.</p></> },
  { id: "termination", title: "Stopping use and access restrictions", content: <p>You may stop using the tools at any time. Closing the page ends the local workspace session; copies you downloaded remain under your control. Access may be restricted for misuse or when legally required. This version has no account deletion or subscription cancellation procedure because it offers neither accounts nor subscriptions.</p> },
  { id: "updates", title: "Changes and disputes", content: <><p>Revisions will carry an updated version and date. Material changes must be communicated appropriately before taking effect. If a provision is unenforceable, the remaining provisions continue to apply to the extent allowed by law.</p><p>This draft does not designate a court or arbitration forum. Applicable mandatory legal protections remain in place. Operator jurisdiction and a monitored channel for support and disputes must be confirmed before these terms take effect.</p></> },
];

export default function Page() {
  return <LegalPage label="Terms of Service" h1="Terms for Using the Metadata Tools" lede="Terms of Service — permitted uses, your responsibilities, and the limits of the current free, browser-based tools." sections={sections} />;
}
