import Link from "next/link";
import { SupportContact } from "@/components/layout/support-contact";
import { LegalPage, type LegalSection } from "@/components/marketing/legal-page";
import { metadataFor, siteUrl } from "@/lib/site";

import { legalDetails } from "@/lib/legal";

export const metadata = metadataFor("/terms");

const sections: LegalSection[] = [
  { id: "scope", title: "About these terms", content: <><p>These terms describe use of AI Metadata Remover’s browser-based image metadata tools at <a href={siteUrl}>aimetadataremover.pro</a>. AI Metadata Remover is operated by {legalDetails.operatorNameLatin} (<span lang="zh-Hans">{legalDetails.operatorName}</span>), an individual based in {legalDetails.operatorLocation} (“we”, “us” or “our”). AI Metadata Remover is the service name, not a separate incorporated company. For support, email <SupportContact />.</p><p>The service is intended for adults aged 18 or older who can enter into an agreement. If you act for an organization, you must be authorized to do so. These terms apply from the effective date shown above. By accessing or using the service, you agree to these terms. If you do not agree, do not use the service.</p></> },
  { id: "service", title: "What the service does", content: <><p>You can inspect supported image metadata, remove supported fields from JPEG and PNG files and download a separate copy. WebP inspection is available; WebP cleaning is not. The tools run in your browser. Google sign-in is available; keep your Google account secure and sign out on shared devices.</p><p>The plans cover metadata cleaning, not AI visual repair or guaranteed removal of every metadata field. The tool does not generate an authenticity certificate, determine copyright ownership or provide a reliable AI detection score. See the <Link href="/metadata-checker">Metadata Checker</Link> and <Link href="/remove-ai-detection-from-image">detection limits</Link> for product details.</p></> },
  { id: "fees", title: "Plans, automatic renewal, cancellation and refunds", content: <><p>The <Link href="/pricing">pricing page</Link> lists the Free, Pro Monthly and Pro Yearly plans. Guests receive one free single-image clean per day; signed-in users receive five per day in total without batch processing. Pro includes unlimited daily image count and batches of up to ten images. Pro Yearly includes up to 30 images per session across three batches. Supported file and batch size limits still apply.</p><h3>Prices and renewal</h3><p>Pro Monthly costs USD $9.90 per month, with USD $4.90 for the first 30 days. Pro Yearly costs USD $89.90 per year, with USD $49.90 for the first 365 days. After the introductory period, the selected plan renews automatically per calendar month or calendar year at its standard price until canceled. Each Google account may use each plan’s introductory offer once; cancellation, refunds or switching plans do not reset eligibility. Free allowances reset at 00:00 UTC and do not roll over. The total due, any applicable taxes and the next renewal date are shown before payment.</p><h3>Cancellation</h3><p>To cancel, sign in, open <Link href="/account/billing">Account billing</Link>, select Cancel auto-renewal, and confirm. Cancel before the next billing date to stop future charges. Cancellation stops future charges; Pro access continues through the end of the paid period. Closing the workspace or signing out does not cancel a subscription. For cancellation assistance, <SupportContact subject="Cancel my subscription" label="contact customer support" />.</p><h3>Refunds</h3><p>For a billing or refund request, <SupportContact subject="Billing or refund request" label="contact customer support" /> with your purchase email and order reference. Do not send payment card details or private images. We review requests under the purchase terms and applicable law; mandatory cancellation, withdrawal and refund rights remain unaffected.</p></> },
  { id: "responsibilities", title: "Your files and responsibilities", content: <><p>Only process files you own or have permission to use and modify. Keep the original and inspect each downloaded copy before publishing or sharing it. You remain responsible for image content, privacy permissions, attribution and any disclosure rules that apply to your use.</p><p>A successful verification concerns the checks the tool actually performs. It does not establish that every private or provenance field is gone, or that another platform will accept or classify the image in a particular way.</p></> },
  { id: "acceptable-use", title: "Permitted and prohibited use", content: <><p>You may use the tools to understand file metadata, remove supported private information or prepare an authorized publishing copy.</p><ul><li>Do not use metadata removal to create false evidence, conceal infringement, impersonate someone or mislead others about an image’s origin.</li><li>Do not violate copyright, privacy, child protection or other applicable laws.</li><li>Do not falsify camera, GPS, capture-date or provenance records, or use the service to remove visible copyright watermarks.</li><li>Do not interfere with the website, exploit its security controls or use it for malicious activity.</li></ul><p>Content Credentials describe provenance; they are not an AI verdict. Optional removal of supported PNG credentials is off by default and does not remove your disclosure obligations.</p></> },
  { id: "breach", title: "Consequences of violating these terms", content: <><p>If you violate the permitted-use rules, including falsifying capture information, misleading others about provenance, or attempting to remove visible copyright watermarks, we may issue a warning, require the misuse to stop, restrict access to affected features, or suspend or terminate access to the service and any associated account. The response will depend on the seriousness and repetition of the conduct. Serious harm, security incidents or legal requirements may require immediate action without advance warning.</p><p>You remain responsible for your conduct and for losses or third-party claims caused by your unlawful use to the extent established under applicable law. We may preserve relevant records and cooperate with lawful requests from authorities. These measures do not give us access to images that stay on your device.</p><p>If you believe a restriction was a mistake, <SupportContact subject="Access restriction review" label="contact customer support" />, identify the account or affected feature, and describe what happened. Do not send passwords, sign-in codes or private image files. We will review the information and explain the outcome. Mandatory consumer rights remain unaffected.</p></> },
  { id: "ownership", title: "Ownership and intellectual property", content: <><p>You retain the rights you already hold in your images. Processing a file does not transfer ownership to AI Metadata Remover or grant you rights held by another person. A cleaned copy does not create new copyright clearance.</p><p>The current local tools do not upload your images, train models on them or require a license to publish them. Rights in the website, software and branding remain with their respective owners, subject to any applicable open-source licenses.</p></> },
  { id: "privacy", title: "Privacy and third-party services", content: <><p>Read the <Link href="/privacy">Privacy Policy</Link> for optional Google sign-in, account and session records, local file processing, temporary diagnostics and ordinary website requests. The current image tools do not depend on a third-party AI generation API or payment checkout.</p><p>External links may lead to services governed by separate terms. AI Metadata Remover does not control how those services handle files you choose to give them.</p></> },
  { id: "limits", title: "Technical limits and availability", content: <><p>Unsupported, damaged, oversized or unusually structured files may be rejected. Some metadata can remain unresolved. Browser memory, device capability and format support can affect processing. Keep backups; the workspace is not a file storage or recovery service.</p><p>Features may be changed or discontinued. Do not rely on uninterrupted access or on the tool as your only way to preserve a file.</p></> },
  { id: "liability", title: "Disclaimers and legal rights", content: <><p>To the extent permitted by applicable law, the tools are provided as available without a guarantee of fitness for a particular purpose, complete metadata removal or a particular detector or platform outcome. They do not provide legal advice or certify authenticity.</p><p>To the extent permitted by law, the operator is not responsible for indirect or consequential losses arising from use of the tools. Nothing in these terms excludes liability that cannot legally be excluded or limits mandatory consumer rights.</p></> },
  { id: "termination", title: "Stopping use and access restrictions", content: <p>You may stop using the tools at any time. Closing the page ends the local workspace session; copies you downloaded remain under your control. Signing out ends your login session but does not delete stored account records. To request account closure and deletion, follow the steps in our <Link href="/privacy#rights">privacy policy</Link>. Cancel a subscription before requesting account closure if you want to stop renewal. Closing the page or signing out does not cancel a paid subscription. Open billing or refund requests must be handled before account deletion; required financial records may need to be retained under applicable law.</p> },
  { id: "updates", title: "Changes and disputes", content: <><p>Revisions will carry an updated version and date. Material changes must be communicated appropriately before taking effect. If a provision is unenforceable, the remaining provisions continue to apply to the extent allowed by law.</p><p>These terms are governed by the laws of the People’s Republic of China, subject to any mandatory consumer protections that apply in your place of residence. Please contact us to seek an informal resolution of a dispute. If it remains unresolved, either party may bring the matter before a court with jurisdiction under applicable law. Nothing in these terms requires mandatory arbitration or removes rights that cannot legally be waived. For support or disputes, email <SupportContact subject="Support or dispute" />.</p></> },
];

export default function Page() {
  return <LegalPage label="Terms of Service" h1="Terms for Using the Metadata Tools" lede="Terms of Service — plans, billing, permitted uses, your responsibilities and the limits of browser-based metadata cleaning." sections={sections} />;
}
