import { build } from "esbuild";
import { Miniflare, convertV4MiniflareOptions } from "miniflare";
import { readFile, mkdir, writeFile } from "node:fs/promises";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";

const bundle = await build({ entryPoints: ["scripts/feedback-d1-qa.worker.ts"], bundle: true, write: false, format: "esm", platform: "neutral", conditions: ["workerd", "worker", "browser"], external: ["node:*"], target: "es2022" });
const mf = new Miniflare(convertV4MiniflareOptions({ modules: true, script: bundle.outputFiles[0].text, compatibilityDate: "2026-09-06", compatibilityFlags: ["nodejs_compat"], d1Databases: { AUTH_DB: "feedback-qa-isolated" }, bindings: { FEEDBACK_RATE_SECRET: "test-only-secret", RESEND_API_KEY: "test-only-never-sent", FEEDBACK_FROM: "feedback@example.com", FEEDBACK_TO: "owner@example.com" } }));
const checks = [];
const pass = name => { checks.push(name); console.log("PASS " + name); };
const base = "http://localhost:3186";
const call = (path, init = {}) => mf.dispatchFetch(base + path, init);
const payload = extra => ({ id: randomUUID(), version: "needs-v1", trigger: "manual", path: "/workspace", outcome: "", need: "", occupation: "", otherOccupation: "", age: "", suggestion: "", email: "", contactConsent: false, ...extra });
const submit = (data, headers = {}, path = "/submit") => call(path, { method: "POST", headers: { origin: base, "content-type": "application/json", "cf-connecting-ip": "192.0.2.1", ...headers }, body: JSON.stringify(data) });
try {
  const db = await mf.getD1Database("AUTH_DB");
  const sql = await readFile("migrations/0002_feedback.sql", "utf8");
  await db.batch(sql.split(";").map(s => s.trim()).filter(Boolean).map(s => db.prepare(s)));
  const data = payload({ occupation: "designer" });
  assert.equal((await submit(data)).status, 201);
  assert.equal((await submit(data)).status, 200);
  assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM feedback_submission").first()).n, 1);
  assert.equal((await submit({ ...data, need: "changed" })).status, 409);
  pass("occupation-only saved in real D1; retry idempotent; changed payload with same ID rejected");
  const row = await db.prepare("SELECT * FROM feedback_submission WHERE id=?").bind(data.id).first();
  assert.equal(row.status, "pending"); assert.equal(row.rate_key.length, 64); assert.ok(!JSON.stringify(row).includes("192.0.2.1"));
  pass("durable outbox exists before mail; IP not stored in plain text");
  assert.equal((await call("/deliver?unconfigured")).status, 200);
  assert.equal((await db.prepare("SELECT attempts FROM feedback_submission WHERE id=?").bind(data.id).first()).attempts, 0);
  await call("/deliver?fail");
  let delivery = await db.prepare("SELECT * FROM feedback_submission WHERE id=?").bind(data.id).first();
  assert.equal(delivery.status, "pending"); assert.equal(delivery.attempts, 1); assert.equal(delivery.last_error, "mail_http_503");
  await db.prepare("UPDATE feedback_submission SET next_attempt_at=0 WHERE id=?").bind(data.id).run();
  await Promise.all([call("/deliver"), call("/deliver")]);
  delivery = await db.prepare("SELECT * FROM feedback_submission WHERE id=?").bind(data.id).first();
  assert.equal(delivery.status, "sent"); assert.equal(delivery.attempts, 2);
  let calls = await (await call("/calls")).json();
  assert.equal(calls.length, 2); assert.equal(calls[0].key, calls[1].key); assert.deepEqual(calls[0].mail, calls[1].mail);
  assert.equal(calls[0].mail.reply_to, undefined); assert.deepEqual(calls[0].mail.to, ["owner@example.com"]);
  pass("missing mail config retains row; provider failure retries; concurrent delivery claims once; stable idempotency key");
  assert.equal((await submit(payload({ need: "bad" }), { origin: "https://evil.example" })).status, 403);
  assert.equal((await submit(payload({ need: "bad" }), { "content-type": "text/plain" })).status, 415);
  assert.equal((await submit(payload({ need: "good", filename: "private.png" }))).status, 400);
  assert.equal((await submit(payload({ need: "good", website: "spam" }))).status, 400);
  assert.equal((await submit(payload({ need: "good" }), {}, "/unconfigured")).status, 503);
  assert.equal((await submit(payload({ need: "x".repeat(17000) }))).status, 413);
  pass("cross-origin, invalid content type, image-related extra fields, honeypot, missing DB and oversized body rejected");
  assert.equal((await submit(data, { origin: "http://127.0.0.1:3186" })).status, 200);
  assert.equal((await submit(data, { origin: "http://127.0.0.1:3187" })).status, 403);
  pass("Next loopback hostname alias accepted only on matching protocol and port");
  const contact = payload({ need: "Task details", email: "visitor@example.com", contactConsent: true });
  assert.equal((await submit(contact)).status, 201); await call("/deliver");
  calls = await (await call("/calls")).json();
  assert.equal(calls.at(-1).mail.reply_to, "visitor@example.com");
  assert.match(calls.at(-1).mail.text, /Task details/);
  assert.equal(calls.at(-1).mail.html, undefined);
  pass("reply-to set only with permission; answers sent as plain text to fixed owner address");
  const parallel = await Promise.all(Array.from({ length: 10 }, () => submit(payload({ age: "25–34" }), { "cf-connecting-ip": "192.0.2.2" })));
  assert.equal(parallel.filter(r => r.status === 201).length, 5);
  assert.equal(parallel.filter(r => r.status === 429).length, 5);
  pass("atomic rate limit accepts exactly five of ten concurrent submissions");
  await db.prepare("UPDATE feedback_submission SET first_attempt_at=?, next_attempt_at=0 WHERE status='pending'").bind(Date.now() - 24 * 3600000).run();
  const before = (await (await call("/calls")).json()).length;
  await call("/deliver");
  assert.equal((await (await call("/calls")).json()).length, before);
  assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM feedback_submission WHERE last_error='retry_window_exhausted'").first()).n, 1);
  pass("expired uncertain delivery is held for review rather than resent beyond idempotency window");
  await mkdir("artifacts/feedback", { recursive: true });
  await writeFile("artifacts/feedback/d1-qa.json", JSON.stringify({ checks, passed: true, realEmailSent: false, note: "Actual workerd D1; mail provider stubbed, no external delivery." }, null, 2));
} finally { await mf.dispose(); }
